### ISSUE TITLE
first_part build fails on step 47.

### ISSUE THREAD

**Issue by AyeYessir** [davegill/wrf-coop#2]
Copying the first_part as our Dockerfile, fails on the line:

> COPY data_smaller.tar /wrf/data_smaller.tar

Step 47/57 : COPY data_smaller.tar /wrf/data_smaller.tar
lstat data_smaller.tar: no such file or directory

I tried inspecting both http://www2.mmm.ucar.edu/wrf/TUTORIAL_DATA/WRF_NCL_scripts.tar.gz and the commented out http://www2.mmm.ucar.edu/wrf/dave/DATA/Data_small/data_SMALL.tar.gz, but could not located where the file is supposed to originate. Please help!

**Comment by AyeYessir** [comment]
Best thing I can figure is it is this is a victim of not allowing conditional COPY statements, as it seems the commented out data_SMALL.tar.gz for the regtest is related to this.

**Comment by AyeYessir** [comment]
I'm just going to do a first-build run that renames "data_smaller.tar" to "data_SMALL.tar.gz" and see what happens after I uncomment the curl statement on line #164 that will download data_SMALL.tar.gz. Lines 164-167 now look like:

RUN if [ "$argname" = "regtest" ]  ; then curl -SL http://www2.mmm.ucar.edu/wrf/dave/DATA/Data_small/data_SMALL.tar.gz | tar -xzC / wrf ; fi
COPY data_SMALL.tar.gz /wrf/data_SMALL.tar.gz 
RUN tar -xf /wrf/data_SMALL.tar.gz  \
     && rm /wrf/data_SMALL.tar.gz

**Comment by AyeYessir** [comment]
Oh I see now... the data is already extracted to the /wrf path from the pipe after the curl, so the COPY, and RUN on data_SMALL.tar.gz shouldn't really even be needed. Commenting out and trying.

**Comment by AyeYessir** [comment]
FYI, simply commenting out the COPY and RUN lines allowed it to build the first-part successfully.

**Comment by davegill** [comment]
@AdamCarlson84 
Adam, 
Would you please open a PR to address this?

**Comment by AyeYessir** [comment]
Hey Dave,

I will definitely open a PR to address it, I just want to ensure that's the
only thing to resolve. kept getting a permission denied error on the
/wrf/wrfoutput path and found that to be an selinux issue... adding a note
about running "*chcon -Rt svirt_sandbox_file_t*" on the output path if
selinux is enabled would be helpful. Now that I just got over that hump,
I'm going to finish going through the tests...

Thanks for putting this all together. My associate Chris Zarzar and Wake
Forest University pointed me toward your git repo. It's going much more
smoothly than my previous attempts to build WRF on our cluster, so thank
you very much!

Do you have any user documentation on using the containers? I am going to
draft something for our faculty member who needs this, which is why I ask.
Thanks,

Adam

**Comment by davegill** [comment]
@AdamCarlson84 
Adam,
If you are not required to build everything from scratch, take a look at the file `Dockerfile-second_part`. It is VERY short. You get to choose what version of WRF you put inside. You could put WPS in the image also.

As for documentation, take a look at a separate repository:
https://github.com/NCAR/WRF_DOCKER
There are README files for both regression testing (what the wrf-coop is really set up for) and for tutorials (includes WPS, WRF, etc).

I much appreciate the feedback that you are providing for corrections.

**Comment by AyeYessir** [comment]
Will definitely need WPS in the image thank you for that.

I will be linking up with my associate to go over testing, since he is
familiar with WRF. I'm just the HPC sysadmin and only have basic knowledge
of the software.

Will be in touch,
Adam
